
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Amigos` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Amigos
 * 
 */
export type AmigosModel = runtime.Types.Result.DefaultSelection<Prisma.$AmigosPayload>

export type AggregateAmigos = {
  _count: AmigosCountAggregateOutputType | null
  _min: AmigosMinAggregateOutputType | null
  _max: AmigosMaxAggregateOutputType | null
}

export type AmigosMinAggregateOutputType = {
  amigo1Id: string | null
  amigo2Id: string | null
}

export type AmigosMaxAggregateOutputType = {
  amigo1Id: string | null
  amigo2Id: string | null
}

export type AmigosCountAggregateOutputType = {
  amigo1Id: number
  amigo2Id: number
  _all: number
}


export type AmigosMinAggregateInputType = {
  amigo1Id?: true
  amigo2Id?: true
}

export type AmigosMaxAggregateInputType = {
  amigo1Id?: true
  amigo2Id?: true
}

export type AmigosCountAggregateInputType = {
  amigo1Id?: true
  amigo2Id?: true
  _all?: true
}

export type AmigosAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Amigos to aggregate.
   */
  where?: Prisma.AmigosWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Amigos to fetch.
   */
  orderBy?: Prisma.AmigosOrderByWithRelationInput | Prisma.AmigosOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AmigosWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Amigos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Amigos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Amigos
  **/
  _count?: true | AmigosCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AmigosMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AmigosMaxAggregateInputType
}

export type GetAmigosAggregateType<T extends AmigosAggregateArgs> = {
      [P in keyof T & keyof AggregateAmigos]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAmigos[P]>
    : Prisma.GetScalarType<T[P], AggregateAmigos[P]>
}




export type AmigosGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AmigosWhereInput
  orderBy?: Prisma.AmigosOrderByWithAggregationInput | Prisma.AmigosOrderByWithAggregationInput[]
  by: Prisma.AmigosScalarFieldEnum[] | Prisma.AmigosScalarFieldEnum
  having?: Prisma.AmigosScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AmigosCountAggregateInputType | true
  _min?: AmigosMinAggregateInputType
  _max?: AmigosMaxAggregateInputType
}

export type AmigosGroupByOutputType = {
  amigo1Id: string
  amigo2Id: string
  _count: AmigosCountAggregateOutputType | null
  _min: AmigosMinAggregateOutputType | null
  _max: AmigosMaxAggregateOutputType | null
}

export type GetAmigosGroupByPayload<T extends AmigosGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AmigosGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AmigosGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AmigosGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AmigosGroupByOutputType[P]>
      }
    >
  >



export type AmigosWhereInput = {
  AND?: Prisma.AmigosWhereInput | Prisma.AmigosWhereInput[]
  OR?: Prisma.AmigosWhereInput[]
  NOT?: Prisma.AmigosWhereInput | Prisma.AmigosWhereInput[]
  amigo1Id?: Prisma.StringFilter<"Amigos"> | string
  amigo2Id?: Prisma.StringFilter<"Amigos"> | string
  amigo1?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  amigo2?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type AmigosOrderByWithRelationInput = {
  amigo1Id?: Prisma.SortOrder
  amigo2Id?: Prisma.SortOrder
  amigo1?: Prisma.UserOrderByWithRelationInput
  amigo2?: Prisma.UserOrderByWithRelationInput
}

export type AmigosWhereUniqueInput = Prisma.AtLeast<{
  amigo1Id_amigo2Id?: Prisma.AmigosAmigo1IdAmigo2IdCompoundUniqueInput
  AND?: Prisma.AmigosWhereInput | Prisma.AmigosWhereInput[]
  OR?: Prisma.AmigosWhereInput[]
  NOT?: Prisma.AmigosWhereInput | Prisma.AmigosWhereInput[]
  amigo1Id?: Prisma.StringFilter<"Amigos"> | string
  amigo2Id?: Prisma.StringFilter<"Amigos"> | string
  amigo1?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  amigo2?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "amigo1Id_amigo2Id">

export type AmigosOrderByWithAggregationInput = {
  amigo1Id?: Prisma.SortOrder
  amigo2Id?: Prisma.SortOrder
  _count?: Prisma.AmigosCountOrderByAggregateInput
  _max?: Prisma.AmigosMaxOrderByAggregateInput
  _min?: Prisma.AmigosMinOrderByAggregateInput
}

export type AmigosScalarWhereWithAggregatesInput = {
  AND?: Prisma.AmigosScalarWhereWithAggregatesInput | Prisma.AmigosScalarWhereWithAggregatesInput[]
  OR?: Prisma.AmigosScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AmigosScalarWhereWithAggregatesInput | Prisma.AmigosScalarWhereWithAggregatesInput[]
  amigo1Id?: Prisma.StringWithAggregatesFilter<"Amigos"> | string
  amigo2Id?: Prisma.StringWithAggregatesFilter<"Amigos"> | string
}

export type AmigosCreateInput = {
  amigo1: Prisma.UserCreateNestedOneWithoutAmizadesIniciadasInput
  amigo2: Prisma.UserCreateNestedOneWithoutAmizadesRecebidasInput
}

export type AmigosUncheckedCreateInput = {
  amigo1Id: string
  amigo2Id: string
}

export type AmigosUpdateInput = {
  amigo1?: Prisma.UserUpdateOneRequiredWithoutAmizadesIniciadasNestedInput
  amigo2?: Prisma.UserUpdateOneRequiredWithoutAmizadesRecebidasNestedInput
}

export type AmigosUncheckedUpdateInput = {
  amigo1Id?: Prisma.StringFieldUpdateOperationsInput | string
  amigo2Id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AmigosCreateManyInput = {
  amigo1Id: string
  amigo2Id: string
}

export type AmigosUpdateManyMutationInput = {

}

export type AmigosUncheckedUpdateManyInput = {
  amigo1Id?: Prisma.StringFieldUpdateOperationsInput | string
  amigo2Id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AmigosListRelationFilter = {
  every?: Prisma.AmigosWhereInput
  some?: Prisma.AmigosWhereInput
  none?: Prisma.AmigosWhereInput
}

export type AmigosOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AmigosAmigo1IdAmigo2IdCompoundUniqueInput = {
  amigo1Id: string
  amigo2Id: string
}

export type AmigosCountOrderByAggregateInput = {
  amigo1Id?: Prisma.SortOrder
  amigo2Id?: Prisma.SortOrder
}

export type AmigosMaxOrderByAggregateInput = {
  amigo1Id?: Prisma.SortOrder
  amigo2Id?: Prisma.SortOrder
}

export type AmigosMinOrderByAggregateInput = {
  amigo1Id?: Prisma.SortOrder
  amigo2Id?: Prisma.SortOrder
}

export type AmigosCreateNestedManyWithoutAmigo1Input = {
  create?: Prisma.XOR<Prisma.AmigosCreateWithoutAmigo1Input, Prisma.AmigosUncheckedCreateWithoutAmigo1Input> | Prisma.AmigosCreateWithoutAmigo1Input[] | Prisma.AmigosUncheckedCreateWithoutAmigo1Input[]
  connectOrCreate?: Prisma.AmigosCreateOrConnectWithoutAmigo1Input | Prisma.AmigosCreateOrConnectWithoutAmigo1Input[]
  createMany?: Prisma.AmigosCreateManyAmigo1InputEnvelope
  connect?: Prisma.AmigosWhereUniqueInput | Prisma.AmigosWhereUniqueInput[]
}

export type AmigosCreateNestedManyWithoutAmigo2Input = {
  create?: Prisma.XOR<Prisma.AmigosCreateWithoutAmigo2Input, Prisma.AmigosUncheckedCreateWithoutAmigo2Input> | Prisma.AmigosCreateWithoutAmigo2Input[] | Prisma.AmigosUncheckedCreateWithoutAmigo2Input[]
  connectOrCreate?: Prisma.AmigosCreateOrConnectWithoutAmigo2Input | Prisma.AmigosCreateOrConnectWithoutAmigo2Input[]
  createMany?: Prisma.AmigosCreateManyAmigo2InputEnvelope
  connect?: Prisma.AmigosWhereUniqueInput | Prisma.AmigosWhereUniqueInput[]
}

export type AmigosUncheckedCreateNestedManyWithoutAmigo1Input = {
  create?: Prisma.XOR<Prisma.AmigosCreateWithoutAmigo1Input, Prisma.AmigosUncheckedCreateWithoutAmigo1Input> | Prisma.AmigosCreateWithoutAmigo1Input[] | Prisma.AmigosUncheckedCreateWithoutAmigo1Input[]
  connectOrCreate?: Prisma.AmigosCreateOrConnectWithoutAmigo1Input | Prisma.AmigosCreateOrConnectWithoutAmigo1Input[]
  createMany?: Prisma.AmigosCreateManyAmigo1InputEnvelope
  connect?: Prisma.AmigosWhereUniqueInput | Prisma.AmigosWhereUniqueInput[]
}

export type AmigosUncheckedCreateNestedManyWithoutAmigo2Input = {
  create?: Prisma.XOR<Prisma.AmigosCreateWithoutAmigo2Input, Prisma.AmigosUncheckedCreateWithoutAmigo2Input> | Prisma.AmigosCreateWithoutAmigo2Input[] | Prisma.AmigosUncheckedCreateWithoutAmigo2Input[]
  connectOrCreate?: Prisma.AmigosCreateOrConnectWithoutAmigo2Input | Prisma.AmigosCreateOrConnectWithoutAmigo2Input[]
  createMany?: Prisma.AmigosCreateManyAmigo2InputEnvelope
  connect?: Prisma.AmigosWhereUniqueInput | Prisma.AmigosWhereUniqueInput[]
}

export type AmigosUpdateManyWithoutAmigo1NestedInput = {
  create?: Prisma.XOR<Prisma.AmigosCreateWithoutAmigo1Input, Prisma.AmigosUncheckedCreateWithoutAmigo1Input> | Prisma.AmigosCreateWithoutAmigo1Input[] | Prisma.AmigosUncheckedCreateWithoutAmigo1Input[]
  connectOrCreate?: Prisma.AmigosCreateOrConnectWithoutAmigo1Input | Prisma.AmigosCreateOrConnectWithoutAmigo1Input[]
  upsert?: Prisma.AmigosUpsertWithWhereUniqueWithoutAmigo1Input | Prisma.AmigosUpsertWithWhereUniqueWithoutAmigo1Input[]
  createMany?: Prisma.AmigosCreateManyAmigo1InputEnvelope
  set?: Prisma.AmigosWhereUniqueInput | Prisma.AmigosWhereUniqueInput[]
  disconnect?: Prisma.AmigosWhereUniqueInput | Prisma.AmigosWhereUniqueInput[]
  delete?: Prisma.AmigosWhereUniqueInput | Prisma.AmigosWhereUniqueInput[]
  connect?: Prisma.AmigosWhereUniqueInput | Prisma.AmigosWhereUniqueInput[]
  update?: Prisma.AmigosUpdateWithWhereUniqueWithoutAmigo1Input | Prisma.AmigosUpdateWithWhereUniqueWithoutAmigo1Input[]
  updateMany?: Prisma.AmigosUpdateManyWithWhereWithoutAmigo1Input | Prisma.AmigosUpdateManyWithWhereWithoutAmigo1Input[]
  deleteMany?: Prisma.AmigosScalarWhereInput | Prisma.AmigosScalarWhereInput[]
}

export type AmigosUpdateManyWithoutAmigo2NestedInput = {
  create?: Prisma.XOR<Prisma.AmigosCreateWithoutAmigo2Input, Prisma.AmigosUncheckedCreateWithoutAmigo2Input> | Prisma.AmigosCreateWithoutAmigo2Input[] | Prisma.AmigosUncheckedCreateWithoutAmigo2Input[]
  connectOrCreate?: Prisma.AmigosCreateOrConnectWithoutAmigo2Input | Prisma.AmigosCreateOrConnectWithoutAmigo2Input[]
  upsert?: Prisma.AmigosUpsertWithWhereUniqueWithoutAmigo2Input | Prisma.AmigosUpsertWithWhereUniqueWithoutAmigo2Input[]
  createMany?: Prisma.AmigosCreateManyAmigo2InputEnvelope
  set?: Prisma.AmigosWhereUniqueInput | Prisma.AmigosWhereUniqueInput[]
  disconnect?: Prisma.AmigosWhereUniqueInput | Prisma.AmigosWhereUniqueInput[]
  delete?: Prisma.AmigosWhereUniqueInput | Prisma.AmigosWhereUniqueInput[]
  connect?: Prisma.AmigosWhereUniqueInput | Prisma.AmigosWhereUniqueInput[]
  update?: Prisma.AmigosUpdateWithWhereUniqueWithoutAmigo2Input | Prisma.AmigosUpdateWithWhereUniqueWithoutAmigo2Input[]
  updateMany?: Prisma.AmigosUpdateManyWithWhereWithoutAmigo2Input | Prisma.AmigosUpdateManyWithWhereWithoutAmigo2Input[]
  deleteMany?: Prisma.AmigosScalarWhereInput | Prisma.AmigosScalarWhereInput[]
}

export type AmigosUncheckedUpdateManyWithoutAmigo1NestedInput = {
  create?: Prisma.XOR<Prisma.AmigosCreateWithoutAmigo1Input, Prisma.AmigosUncheckedCreateWithoutAmigo1Input> | Prisma.AmigosCreateWithoutAmigo1Input[] | Prisma.AmigosUncheckedCreateWithoutAmigo1Input[]
  connectOrCreate?: Prisma.AmigosCreateOrConnectWithoutAmigo1Input | Prisma.AmigosCreateOrConnectWithoutAmigo1Input[]
  upsert?: Prisma.AmigosUpsertWithWhereUniqueWithoutAmigo1Input | Prisma.AmigosUpsertWithWhereUniqueWithoutAmigo1Input[]
  createMany?: Prisma.AmigosCreateManyAmigo1InputEnvelope
  set?: Prisma.AmigosWhereUniqueInput | Prisma.AmigosWhereUniqueInput[]
  disconnect?: Prisma.AmigosWhereUniqueInput | Prisma.AmigosWhereUniqueInput[]
  delete?: Prisma.AmigosWhereUniqueInput | Prisma.AmigosWhereUniqueInput[]
  connect?: Prisma.AmigosWhereUniqueInput | Prisma.AmigosWhereUniqueInput[]
  update?: Prisma.AmigosUpdateWithWhereUniqueWithoutAmigo1Input | Prisma.AmigosUpdateWithWhereUniqueWithoutAmigo1Input[]
  updateMany?: Prisma.AmigosUpdateManyWithWhereWithoutAmigo1Input | Prisma.AmigosUpdateManyWithWhereWithoutAmigo1Input[]
  deleteMany?: Prisma.AmigosScalarWhereInput | Prisma.AmigosScalarWhereInput[]
}

export type AmigosUncheckedUpdateManyWithoutAmigo2NestedInput = {
  create?: Prisma.XOR<Prisma.AmigosCreateWithoutAmigo2Input, Prisma.AmigosUncheckedCreateWithoutAmigo2Input> | Prisma.AmigosCreateWithoutAmigo2Input[] | Prisma.AmigosUncheckedCreateWithoutAmigo2Input[]
  connectOrCreate?: Prisma.AmigosCreateOrConnectWithoutAmigo2Input | Prisma.AmigosCreateOrConnectWithoutAmigo2Input[]
  upsert?: Prisma.AmigosUpsertWithWhereUniqueWithoutAmigo2Input | Prisma.AmigosUpsertWithWhereUniqueWithoutAmigo2Input[]
  createMany?: Prisma.AmigosCreateManyAmigo2InputEnvelope
  set?: Prisma.AmigosWhereUniqueInput | Prisma.AmigosWhereUniqueInput[]
  disconnect?: Prisma.AmigosWhereUniqueInput | Prisma.AmigosWhereUniqueInput[]
  delete?: Prisma.AmigosWhereUniqueInput | Prisma.AmigosWhereUniqueInput[]
  connect?: Prisma.AmigosWhereUniqueInput | Prisma.AmigosWhereUniqueInput[]
  update?: Prisma.AmigosUpdateWithWhereUniqueWithoutAmigo2Input | Prisma.AmigosUpdateWithWhereUniqueWithoutAmigo2Input[]
  updateMany?: Prisma.AmigosUpdateManyWithWhereWithoutAmigo2Input | Prisma.AmigosUpdateManyWithWhereWithoutAmigo2Input[]
  deleteMany?: Prisma.AmigosScalarWhereInput | Prisma.AmigosScalarWhereInput[]
}

export type AmigosCreateWithoutAmigo1Input = {
  amigo2: Prisma.UserCreateNestedOneWithoutAmizadesRecebidasInput
}

export type AmigosUncheckedCreateWithoutAmigo1Input = {
  amigo2Id: string
}

export type AmigosCreateOrConnectWithoutAmigo1Input = {
  where: Prisma.AmigosWhereUniqueInput
  create: Prisma.XOR<Prisma.AmigosCreateWithoutAmigo1Input, Prisma.AmigosUncheckedCreateWithoutAmigo1Input>
}

export type AmigosCreateManyAmigo1InputEnvelope = {
  data: Prisma.AmigosCreateManyAmigo1Input | Prisma.AmigosCreateManyAmigo1Input[]
  skipDuplicates?: boolean
}

export type AmigosCreateWithoutAmigo2Input = {
  amigo1: Prisma.UserCreateNestedOneWithoutAmizadesIniciadasInput
}

export type AmigosUncheckedCreateWithoutAmigo2Input = {
  amigo1Id: string
}

export type AmigosCreateOrConnectWithoutAmigo2Input = {
  where: Prisma.AmigosWhereUniqueInput
  create: Prisma.XOR<Prisma.AmigosCreateWithoutAmigo2Input, Prisma.AmigosUncheckedCreateWithoutAmigo2Input>
}

export type AmigosCreateManyAmigo2InputEnvelope = {
  data: Prisma.AmigosCreateManyAmigo2Input | Prisma.AmigosCreateManyAmigo2Input[]
  skipDuplicates?: boolean
}

export type AmigosUpsertWithWhereUniqueWithoutAmigo1Input = {
  where: Prisma.AmigosWhereUniqueInput
  update: Prisma.XOR<Prisma.AmigosUpdateWithoutAmigo1Input, Prisma.AmigosUncheckedUpdateWithoutAmigo1Input>
  create: Prisma.XOR<Prisma.AmigosCreateWithoutAmigo1Input, Prisma.AmigosUncheckedCreateWithoutAmigo1Input>
}

export type AmigosUpdateWithWhereUniqueWithoutAmigo1Input = {
  where: Prisma.AmigosWhereUniqueInput
  data: Prisma.XOR<Prisma.AmigosUpdateWithoutAmigo1Input, Prisma.AmigosUncheckedUpdateWithoutAmigo1Input>
}

export type AmigosUpdateManyWithWhereWithoutAmigo1Input = {
  where: Prisma.AmigosScalarWhereInput
  data: Prisma.XOR<Prisma.AmigosUpdateManyMutationInput, Prisma.AmigosUncheckedUpdateManyWithoutAmigo1Input>
}

export type AmigosScalarWhereInput = {
  AND?: Prisma.AmigosScalarWhereInput | Prisma.AmigosScalarWhereInput[]
  OR?: Prisma.AmigosScalarWhereInput[]
  NOT?: Prisma.AmigosScalarWhereInput | Prisma.AmigosScalarWhereInput[]
  amigo1Id?: Prisma.StringFilter<"Amigos"> | string
  amigo2Id?: Prisma.StringFilter<"Amigos"> | string
}

export type AmigosUpsertWithWhereUniqueWithoutAmigo2Input = {
  where: Prisma.AmigosWhereUniqueInput
  update: Prisma.XOR<Prisma.AmigosUpdateWithoutAmigo2Input, Prisma.AmigosUncheckedUpdateWithoutAmigo2Input>
  create: Prisma.XOR<Prisma.AmigosCreateWithoutAmigo2Input, Prisma.AmigosUncheckedCreateWithoutAmigo2Input>
}

export type AmigosUpdateWithWhereUniqueWithoutAmigo2Input = {
  where: Prisma.AmigosWhereUniqueInput
  data: Prisma.XOR<Prisma.AmigosUpdateWithoutAmigo2Input, Prisma.AmigosUncheckedUpdateWithoutAmigo2Input>
}

export type AmigosUpdateManyWithWhereWithoutAmigo2Input = {
  where: Prisma.AmigosScalarWhereInput
  data: Prisma.XOR<Prisma.AmigosUpdateManyMutationInput, Prisma.AmigosUncheckedUpdateManyWithoutAmigo2Input>
}

export type AmigosCreateManyAmigo1Input = {
  amigo2Id: string
}

export type AmigosCreateManyAmigo2Input = {
  amigo1Id: string
}

export type AmigosUpdateWithoutAmigo1Input = {
  amigo2?: Prisma.UserUpdateOneRequiredWithoutAmizadesRecebidasNestedInput
}

export type AmigosUncheckedUpdateWithoutAmigo1Input = {
  amigo2Id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AmigosUncheckedUpdateManyWithoutAmigo1Input = {
  amigo2Id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AmigosUpdateWithoutAmigo2Input = {
  amigo1?: Prisma.UserUpdateOneRequiredWithoutAmizadesIniciadasNestedInput
}

export type AmigosUncheckedUpdateWithoutAmigo2Input = {
  amigo1Id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AmigosUncheckedUpdateManyWithoutAmigo2Input = {
  amigo1Id?: Prisma.StringFieldUpdateOperationsInput | string
}



export type AmigosSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  amigo1Id?: boolean
  amigo2Id?: boolean
  amigo1?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  amigo2?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["amigos"]>

export type AmigosSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  amigo1Id?: boolean
  amigo2Id?: boolean
  amigo1?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  amigo2?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["amigos"]>

export type AmigosSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  amigo1Id?: boolean
  amigo2Id?: boolean
  amigo1?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  amigo2?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["amigos"]>

export type AmigosSelectScalar = {
  amigo1Id?: boolean
  amigo2Id?: boolean
}

export type AmigosOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"amigo1Id" | "amigo2Id", ExtArgs["result"]["amigos"]>
export type AmigosInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  amigo1?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  amigo2?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type AmigosIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  amigo1?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  amigo2?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type AmigosIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  amigo1?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  amigo2?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $AmigosPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Amigos"
  objects: {
    amigo1: Prisma.$UserPayload<ExtArgs>
    amigo2: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    amigo1Id: string
    amigo2Id: string
  }, ExtArgs["result"]["amigos"]>
  composites: {}
}

export type AmigosGetPayload<S extends boolean | null | undefined | AmigosDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AmigosPayload, S>

export type AmigosCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AmigosFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AmigosCountAggregateInputType | true
  }

export interface AmigosDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Amigos'], meta: { name: 'Amigos' } }
  /**
   * Find zero or one Amigos that matches the filter.
   * @param {AmigosFindUniqueArgs} args - Arguments to find a Amigos
   * @example
   * // Get one Amigos
   * const amigos = await prisma.amigos.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AmigosFindUniqueArgs>(args: Prisma.SelectSubset<T, AmigosFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AmigosClient<runtime.Types.Result.GetResult<Prisma.$AmigosPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Amigos that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AmigosFindUniqueOrThrowArgs} args - Arguments to find a Amigos
   * @example
   * // Get one Amigos
   * const amigos = await prisma.amigos.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AmigosFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AmigosFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AmigosClient<runtime.Types.Result.GetResult<Prisma.$AmigosPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Amigos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AmigosFindFirstArgs} args - Arguments to find a Amigos
   * @example
   * // Get one Amigos
   * const amigos = await prisma.amigos.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AmigosFindFirstArgs>(args?: Prisma.SelectSubset<T, AmigosFindFirstArgs<ExtArgs>>): Prisma.Prisma__AmigosClient<runtime.Types.Result.GetResult<Prisma.$AmigosPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Amigos that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AmigosFindFirstOrThrowArgs} args - Arguments to find a Amigos
   * @example
   * // Get one Amigos
   * const amigos = await prisma.amigos.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AmigosFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AmigosFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AmigosClient<runtime.Types.Result.GetResult<Prisma.$AmigosPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Amigos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AmigosFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Amigos
   * const amigos = await prisma.amigos.findMany()
   * 
   * // Get first 10 Amigos
   * const amigos = await prisma.amigos.findMany({ take: 10 })
   * 
   * // Only select the `amigo1Id`
   * const amigosWithAmigo1IdOnly = await prisma.amigos.findMany({ select: { amigo1Id: true } })
   * 
   */
  findMany<T extends AmigosFindManyArgs>(args?: Prisma.SelectSubset<T, AmigosFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AmigosPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Amigos.
   * @param {AmigosCreateArgs} args - Arguments to create a Amigos.
   * @example
   * // Create one Amigos
   * const Amigos = await prisma.amigos.create({
   *   data: {
   *     // ... data to create a Amigos
   *   }
   * })
   * 
   */
  create<T extends AmigosCreateArgs>(args: Prisma.SelectSubset<T, AmigosCreateArgs<ExtArgs>>): Prisma.Prisma__AmigosClient<runtime.Types.Result.GetResult<Prisma.$AmigosPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Amigos.
   * @param {AmigosCreateManyArgs} args - Arguments to create many Amigos.
   * @example
   * // Create many Amigos
   * const amigos = await prisma.amigos.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AmigosCreateManyArgs>(args?: Prisma.SelectSubset<T, AmigosCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Amigos and returns the data saved in the database.
   * @param {AmigosCreateManyAndReturnArgs} args - Arguments to create many Amigos.
   * @example
   * // Create many Amigos
   * const amigos = await prisma.amigos.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Amigos and only return the `amigo1Id`
   * const amigosWithAmigo1IdOnly = await prisma.amigos.createManyAndReturn({
   *   select: { amigo1Id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AmigosCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AmigosCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AmigosPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Amigos.
   * @param {AmigosDeleteArgs} args - Arguments to delete one Amigos.
   * @example
   * // Delete one Amigos
   * const Amigos = await prisma.amigos.delete({
   *   where: {
   *     // ... filter to delete one Amigos
   *   }
   * })
   * 
   */
  delete<T extends AmigosDeleteArgs>(args: Prisma.SelectSubset<T, AmigosDeleteArgs<ExtArgs>>): Prisma.Prisma__AmigosClient<runtime.Types.Result.GetResult<Prisma.$AmigosPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Amigos.
   * @param {AmigosUpdateArgs} args - Arguments to update one Amigos.
   * @example
   * // Update one Amigos
   * const amigos = await prisma.amigos.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AmigosUpdateArgs>(args: Prisma.SelectSubset<T, AmigosUpdateArgs<ExtArgs>>): Prisma.Prisma__AmigosClient<runtime.Types.Result.GetResult<Prisma.$AmigosPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Amigos.
   * @param {AmigosDeleteManyArgs} args - Arguments to filter Amigos to delete.
   * @example
   * // Delete a few Amigos
   * const { count } = await prisma.amigos.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AmigosDeleteManyArgs>(args?: Prisma.SelectSubset<T, AmigosDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Amigos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AmigosUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Amigos
   * const amigos = await prisma.amigos.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AmigosUpdateManyArgs>(args: Prisma.SelectSubset<T, AmigosUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Amigos and returns the data updated in the database.
   * @param {AmigosUpdateManyAndReturnArgs} args - Arguments to update many Amigos.
   * @example
   * // Update many Amigos
   * const amigos = await prisma.amigos.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Amigos and only return the `amigo1Id`
   * const amigosWithAmigo1IdOnly = await prisma.amigos.updateManyAndReturn({
   *   select: { amigo1Id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AmigosUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AmigosUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AmigosPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Amigos.
   * @param {AmigosUpsertArgs} args - Arguments to update or create a Amigos.
   * @example
   * // Update or create a Amigos
   * const amigos = await prisma.amigos.upsert({
   *   create: {
   *     // ... data to create a Amigos
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Amigos we want to update
   *   }
   * })
   */
  upsert<T extends AmigosUpsertArgs>(args: Prisma.SelectSubset<T, AmigosUpsertArgs<ExtArgs>>): Prisma.Prisma__AmigosClient<runtime.Types.Result.GetResult<Prisma.$AmigosPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Amigos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AmigosCountArgs} args - Arguments to filter Amigos to count.
   * @example
   * // Count the number of Amigos
   * const count = await prisma.amigos.count({
   *   where: {
   *     // ... the filter for the Amigos we want to count
   *   }
   * })
  **/
  count<T extends AmigosCountArgs>(
    args?: Prisma.Subset<T, AmigosCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AmigosCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Amigos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AmigosAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AmigosAggregateArgs>(args: Prisma.Subset<T, AmigosAggregateArgs>): Prisma.PrismaPromise<GetAmigosAggregateType<T>>

  /**
   * Group by Amigos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AmigosGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AmigosGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AmigosGroupByArgs['orderBy'] }
      : { orderBy?: AmigosGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AmigosGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAmigosGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Amigos model
 */
readonly fields: AmigosFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Amigos.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AmigosClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  amigo1<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  amigo2<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Amigos model
 */
export interface AmigosFieldRefs {
  readonly amigo1Id: Prisma.FieldRef<"Amigos", 'String'>
  readonly amigo2Id: Prisma.FieldRef<"Amigos", 'String'>
}
    

// Custom InputTypes
/**
 * Amigos findUnique
 */
export type AmigosFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Amigos
   */
  select?: Prisma.AmigosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Amigos
   */
  omit?: Prisma.AmigosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AmigosInclude<ExtArgs> | null
  /**
   * Filter, which Amigos to fetch.
   */
  where: Prisma.AmigosWhereUniqueInput
}

/**
 * Amigos findUniqueOrThrow
 */
export type AmigosFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Amigos
   */
  select?: Prisma.AmigosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Amigos
   */
  omit?: Prisma.AmigosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AmigosInclude<ExtArgs> | null
  /**
   * Filter, which Amigos to fetch.
   */
  where: Prisma.AmigosWhereUniqueInput
}

/**
 * Amigos findFirst
 */
export type AmigosFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Amigos
   */
  select?: Prisma.AmigosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Amigos
   */
  omit?: Prisma.AmigosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AmigosInclude<ExtArgs> | null
  /**
   * Filter, which Amigos to fetch.
   */
  where?: Prisma.AmigosWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Amigos to fetch.
   */
  orderBy?: Prisma.AmigosOrderByWithRelationInput | Prisma.AmigosOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Amigos.
   */
  cursor?: Prisma.AmigosWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Amigos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Amigos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Amigos.
   */
  distinct?: Prisma.AmigosScalarFieldEnum | Prisma.AmigosScalarFieldEnum[]
}

/**
 * Amigos findFirstOrThrow
 */
export type AmigosFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Amigos
   */
  select?: Prisma.AmigosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Amigos
   */
  omit?: Prisma.AmigosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AmigosInclude<ExtArgs> | null
  /**
   * Filter, which Amigos to fetch.
   */
  where?: Prisma.AmigosWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Amigos to fetch.
   */
  orderBy?: Prisma.AmigosOrderByWithRelationInput | Prisma.AmigosOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Amigos.
   */
  cursor?: Prisma.AmigosWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Amigos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Amigos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Amigos.
   */
  distinct?: Prisma.AmigosScalarFieldEnum | Prisma.AmigosScalarFieldEnum[]
}

/**
 * Amigos findMany
 */
export type AmigosFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Amigos
   */
  select?: Prisma.AmigosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Amigos
   */
  omit?: Prisma.AmigosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AmigosInclude<ExtArgs> | null
  /**
   * Filter, which Amigos to fetch.
   */
  where?: Prisma.AmigosWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Amigos to fetch.
   */
  orderBy?: Prisma.AmigosOrderByWithRelationInput | Prisma.AmigosOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Amigos.
   */
  cursor?: Prisma.AmigosWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Amigos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Amigos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Amigos.
   */
  distinct?: Prisma.AmigosScalarFieldEnum | Prisma.AmigosScalarFieldEnum[]
}

/**
 * Amigos create
 */
export type AmigosCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Amigos
   */
  select?: Prisma.AmigosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Amigos
   */
  omit?: Prisma.AmigosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AmigosInclude<ExtArgs> | null
  /**
   * The data needed to create a Amigos.
   */
  data: Prisma.XOR<Prisma.AmigosCreateInput, Prisma.AmigosUncheckedCreateInput>
}

/**
 * Amigos createMany
 */
export type AmigosCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Amigos.
   */
  data: Prisma.AmigosCreateManyInput | Prisma.AmigosCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Amigos createManyAndReturn
 */
export type AmigosCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Amigos
   */
  select?: Prisma.AmigosSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Amigos
   */
  omit?: Prisma.AmigosOmit<ExtArgs> | null
  /**
   * The data used to create many Amigos.
   */
  data: Prisma.AmigosCreateManyInput | Prisma.AmigosCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AmigosIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Amigos update
 */
export type AmigosUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Amigos
   */
  select?: Prisma.AmigosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Amigos
   */
  omit?: Prisma.AmigosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AmigosInclude<ExtArgs> | null
  /**
   * The data needed to update a Amigos.
   */
  data: Prisma.XOR<Prisma.AmigosUpdateInput, Prisma.AmigosUncheckedUpdateInput>
  /**
   * Choose, which Amigos to update.
   */
  where: Prisma.AmigosWhereUniqueInput
}

/**
 * Amigos updateMany
 */
export type AmigosUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Amigos.
   */
  data: Prisma.XOR<Prisma.AmigosUpdateManyMutationInput, Prisma.AmigosUncheckedUpdateManyInput>
  /**
   * Filter which Amigos to update
   */
  where?: Prisma.AmigosWhereInput
  /**
   * Limit how many Amigos to update.
   */
  limit?: number
}

/**
 * Amigos updateManyAndReturn
 */
export type AmigosUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Amigos
   */
  select?: Prisma.AmigosSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Amigos
   */
  omit?: Prisma.AmigosOmit<ExtArgs> | null
  /**
   * The data used to update Amigos.
   */
  data: Prisma.XOR<Prisma.AmigosUpdateManyMutationInput, Prisma.AmigosUncheckedUpdateManyInput>
  /**
   * Filter which Amigos to update
   */
  where?: Prisma.AmigosWhereInput
  /**
   * Limit how many Amigos to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AmigosIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Amigos upsert
 */
export type AmigosUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Amigos
   */
  select?: Prisma.AmigosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Amigos
   */
  omit?: Prisma.AmigosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AmigosInclude<ExtArgs> | null
  /**
   * The filter to search for the Amigos to update in case it exists.
   */
  where: Prisma.AmigosWhereUniqueInput
  /**
   * In case the Amigos found by the `where` argument doesn't exist, create a new Amigos with this data.
   */
  create: Prisma.XOR<Prisma.AmigosCreateInput, Prisma.AmigosUncheckedCreateInput>
  /**
   * In case the Amigos was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AmigosUpdateInput, Prisma.AmigosUncheckedUpdateInput>
}

/**
 * Amigos delete
 */
export type AmigosDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Amigos
   */
  select?: Prisma.AmigosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Amigos
   */
  omit?: Prisma.AmigosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AmigosInclude<ExtArgs> | null
  /**
   * Filter which Amigos to delete.
   */
  where: Prisma.AmigosWhereUniqueInput
}

/**
 * Amigos deleteMany
 */
export type AmigosDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Amigos to delete
   */
  where?: Prisma.AmigosWhereInput
  /**
   * Limit how many Amigos to delete.
   */
  limit?: number
}

/**
 * Amigos without action
 */
export type AmigosDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Amigos
   */
  select?: Prisma.AmigosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Amigos
   */
  omit?: Prisma.AmigosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AmigosInclude<ExtArgs> | null
}
