
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Escrito_por` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Escrito_por
 * 
 */
export type Escrito_porModel = runtime.Types.Result.DefaultSelection<Prisma.$Escrito_porPayload>

export type AggregateEscrito_por = {
  _count: Escrito_porCountAggregateOutputType | null
  _avg: Escrito_porAvgAggregateOutputType | null
  _sum: Escrito_porSumAggregateOutputType | null
  _min: Escrito_porMinAggregateOutputType | null
  _max: Escrito_porMaxAggregateOutputType | null
}

export type Escrito_porAvgAggregateOutputType = {
  livroId: number | null
  autorId: number | null
}

export type Escrito_porSumAggregateOutputType = {
  livroId: number | null
  autorId: number | null
}

export type Escrito_porMinAggregateOutputType = {
  livroId: number | null
  autorId: number | null
}

export type Escrito_porMaxAggregateOutputType = {
  livroId: number | null
  autorId: number | null
}

export type Escrito_porCountAggregateOutputType = {
  livroId: number
  autorId: number
  _all: number
}


export type Escrito_porAvgAggregateInputType = {
  livroId?: true
  autorId?: true
}

export type Escrito_porSumAggregateInputType = {
  livroId?: true
  autorId?: true
}

export type Escrito_porMinAggregateInputType = {
  livroId?: true
  autorId?: true
}

export type Escrito_porMaxAggregateInputType = {
  livroId?: true
  autorId?: true
}

export type Escrito_porCountAggregateInputType = {
  livroId?: true
  autorId?: true
  _all?: true
}

export type Escrito_porAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Escrito_por to aggregate.
   */
  where?: Prisma.Escrito_porWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Escrito_pors to fetch.
   */
  orderBy?: Prisma.Escrito_porOrderByWithRelationInput | Prisma.Escrito_porOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.Escrito_porWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Escrito_pors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Escrito_pors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Escrito_pors
  **/
  _count?: true | Escrito_porCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Escrito_porAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Escrito_porSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Escrito_porMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Escrito_porMaxAggregateInputType
}

export type GetEscrito_porAggregateType<T extends Escrito_porAggregateArgs> = {
      [P in keyof T & keyof AggregateEscrito_por]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEscrito_por[P]>
    : Prisma.GetScalarType<T[P], AggregateEscrito_por[P]>
}




export type Escrito_porGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.Escrito_porWhereInput
  orderBy?: Prisma.Escrito_porOrderByWithAggregationInput | Prisma.Escrito_porOrderByWithAggregationInput[]
  by: Prisma.Escrito_porScalarFieldEnum[] | Prisma.Escrito_porScalarFieldEnum
  having?: Prisma.Escrito_porScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Escrito_porCountAggregateInputType | true
  _avg?: Escrito_porAvgAggregateInputType
  _sum?: Escrito_porSumAggregateInputType
  _min?: Escrito_porMinAggregateInputType
  _max?: Escrito_porMaxAggregateInputType
}

export type Escrito_porGroupByOutputType = {
  livroId: number
  autorId: number
  _count: Escrito_porCountAggregateOutputType | null
  _avg: Escrito_porAvgAggregateOutputType | null
  _sum: Escrito_porSumAggregateOutputType | null
  _min: Escrito_porMinAggregateOutputType | null
  _max: Escrito_porMaxAggregateOutputType | null
}

export type GetEscrito_porGroupByPayload<T extends Escrito_porGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Escrito_porGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Escrito_porGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Escrito_porGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Escrito_porGroupByOutputType[P]>
      }
    >
  >



export type Escrito_porWhereInput = {
  AND?: Prisma.Escrito_porWhereInput | Prisma.Escrito_porWhereInput[]
  OR?: Prisma.Escrito_porWhereInput[]
  NOT?: Prisma.Escrito_porWhereInput | Prisma.Escrito_porWhereInput[]
  livroId?: Prisma.IntFilter<"Escrito_por"> | number
  autorId?: Prisma.IntFilter<"Escrito_por"> | number
  autor?: Prisma.XOR<Prisma.AutorScalarRelationFilter, Prisma.AutorWhereInput>
  livro?: Prisma.XOR<Prisma.LivroScalarRelationFilter, Prisma.LivroWhereInput>
}

export type Escrito_porOrderByWithRelationInput = {
  livroId?: Prisma.SortOrder
  autorId?: Prisma.SortOrder
  autor?: Prisma.AutorOrderByWithRelationInput
  livro?: Prisma.LivroOrderByWithRelationInput
}

export type Escrito_porWhereUniqueInput = Prisma.AtLeast<{
  livroId_autorId?: Prisma.Escrito_porLivroIdAutorIdCompoundUniqueInput
  AND?: Prisma.Escrito_porWhereInput | Prisma.Escrito_porWhereInput[]
  OR?: Prisma.Escrito_porWhereInput[]
  NOT?: Prisma.Escrito_porWhereInput | Prisma.Escrito_porWhereInput[]
  livroId?: Prisma.IntFilter<"Escrito_por"> | number
  autorId?: Prisma.IntFilter<"Escrito_por"> | number
  autor?: Prisma.XOR<Prisma.AutorScalarRelationFilter, Prisma.AutorWhereInput>
  livro?: Prisma.XOR<Prisma.LivroScalarRelationFilter, Prisma.LivroWhereInput>
}, "livroId_autorId">

export type Escrito_porOrderByWithAggregationInput = {
  livroId?: Prisma.SortOrder
  autorId?: Prisma.SortOrder
  _count?: Prisma.Escrito_porCountOrderByAggregateInput
  _avg?: Prisma.Escrito_porAvgOrderByAggregateInput
  _max?: Prisma.Escrito_porMaxOrderByAggregateInput
  _min?: Prisma.Escrito_porMinOrderByAggregateInput
  _sum?: Prisma.Escrito_porSumOrderByAggregateInput
}

export type Escrito_porScalarWhereWithAggregatesInput = {
  AND?: Prisma.Escrito_porScalarWhereWithAggregatesInput | Prisma.Escrito_porScalarWhereWithAggregatesInput[]
  OR?: Prisma.Escrito_porScalarWhereWithAggregatesInput[]
  NOT?: Prisma.Escrito_porScalarWhereWithAggregatesInput | Prisma.Escrito_porScalarWhereWithAggregatesInput[]
  livroId?: Prisma.IntWithAggregatesFilter<"Escrito_por"> | number
  autorId?: Prisma.IntWithAggregatesFilter<"Escrito_por"> | number
}

export type Escrito_porCreateInput = {
  autor: Prisma.AutorCreateNestedOneWithoutLivrosInput
  livro: Prisma.LivroCreateNestedOneWithoutAutoresInput
}

export type Escrito_porUncheckedCreateInput = {
  livroId: number
  autorId: number
}

export type Escrito_porUpdateInput = {
  autor?: Prisma.AutorUpdateOneRequiredWithoutLivrosNestedInput
  livro?: Prisma.LivroUpdateOneRequiredWithoutAutoresNestedInput
}

export type Escrito_porUncheckedUpdateInput = {
  livroId?: Prisma.IntFieldUpdateOperationsInput | number
  autorId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type Escrito_porCreateManyInput = {
  livroId: number
  autorId: number
}

export type Escrito_porUpdateManyMutationInput = {

}

export type Escrito_porUncheckedUpdateManyInput = {
  livroId?: Prisma.IntFieldUpdateOperationsInput | number
  autorId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type Escrito_porListRelationFilter = {
  every?: Prisma.Escrito_porWhereInput
  some?: Prisma.Escrito_porWhereInput
  none?: Prisma.Escrito_porWhereInput
}

export type Escrito_porOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type Escrito_porLivroIdAutorIdCompoundUniqueInput = {
  livroId: number
  autorId: number
}

export type Escrito_porCountOrderByAggregateInput = {
  livroId?: Prisma.SortOrder
  autorId?: Prisma.SortOrder
}

export type Escrito_porAvgOrderByAggregateInput = {
  livroId?: Prisma.SortOrder
  autorId?: Prisma.SortOrder
}

export type Escrito_porMaxOrderByAggregateInput = {
  livroId?: Prisma.SortOrder
  autorId?: Prisma.SortOrder
}

export type Escrito_porMinOrderByAggregateInput = {
  livroId?: Prisma.SortOrder
  autorId?: Prisma.SortOrder
}

export type Escrito_porSumOrderByAggregateInput = {
  livroId?: Prisma.SortOrder
  autorId?: Prisma.SortOrder
}

export type Escrito_porCreateNestedManyWithoutLivroInput = {
  create?: Prisma.XOR<Prisma.Escrito_porCreateWithoutLivroInput, Prisma.Escrito_porUncheckedCreateWithoutLivroInput> | Prisma.Escrito_porCreateWithoutLivroInput[] | Prisma.Escrito_porUncheckedCreateWithoutLivroInput[]
  connectOrCreate?: Prisma.Escrito_porCreateOrConnectWithoutLivroInput | Prisma.Escrito_porCreateOrConnectWithoutLivroInput[]
  createMany?: Prisma.Escrito_porCreateManyLivroInputEnvelope
  connect?: Prisma.Escrito_porWhereUniqueInput | Prisma.Escrito_porWhereUniqueInput[]
}

export type Escrito_porUncheckedCreateNestedManyWithoutLivroInput = {
  create?: Prisma.XOR<Prisma.Escrito_porCreateWithoutLivroInput, Prisma.Escrito_porUncheckedCreateWithoutLivroInput> | Prisma.Escrito_porCreateWithoutLivroInput[] | Prisma.Escrito_porUncheckedCreateWithoutLivroInput[]
  connectOrCreate?: Prisma.Escrito_porCreateOrConnectWithoutLivroInput | Prisma.Escrito_porCreateOrConnectWithoutLivroInput[]
  createMany?: Prisma.Escrito_porCreateManyLivroInputEnvelope
  connect?: Prisma.Escrito_porWhereUniqueInput | Prisma.Escrito_porWhereUniqueInput[]
}

export type Escrito_porUpdateManyWithoutLivroNestedInput = {
  create?: Prisma.XOR<Prisma.Escrito_porCreateWithoutLivroInput, Prisma.Escrito_porUncheckedCreateWithoutLivroInput> | Prisma.Escrito_porCreateWithoutLivroInput[] | Prisma.Escrito_porUncheckedCreateWithoutLivroInput[]
  connectOrCreate?: Prisma.Escrito_porCreateOrConnectWithoutLivroInput | Prisma.Escrito_porCreateOrConnectWithoutLivroInput[]
  upsert?: Prisma.Escrito_porUpsertWithWhereUniqueWithoutLivroInput | Prisma.Escrito_porUpsertWithWhereUniqueWithoutLivroInput[]
  createMany?: Prisma.Escrito_porCreateManyLivroInputEnvelope
  set?: Prisma.Escrito_porWhereUniqueInput | Prisma.Escrito_porWhereUniqueInput[]
  disconnect?: Prisma.Escrito_porWhereUniqueInput | Prisma.Escrito_porWhereUniqueInput[]
  delete?: Prisma.Escrito_porWhereUniqueInput | Prisma.Escrito_porWhereUniqueInput[]
  connect?: Prisma.Escrito_porWhereUniqueInput | Prisma.Escrito_porWhereUniqueInput[]
  update?: Prisma.Escrito_porUpdateWithWhereUniqueWithoutLivroInput | Prisma.Escrito_porUpdateWithWhereUniqueWithoutLivroInput[]
  updateMany?: Prisma.Escrito_porUpdateManyWithWhereWithoutLivroInput | Prisma.Escrito_porUpdateManyWithWhereWithoutLivroInput[]
  deleteMany?: Prisma.Escrito_porScalarWhereInput | Prisma.Escrito_porScalarWhereInput[]
}

export type Escrito_porUncheckedUpdateManyWithoutLivroNestedInput = {
  create?: Prisma.XOR<Prisma.Escrito_porCreateWithoutLivroInput, Prisma.Escrito_porUncheckedCreateWithoutLivroInput> | Prisma.Escrito_porCreateWithoutLivroInput[] | Prisma.Escrito_porUncheckedCreateWithoutLivroInput[]
  connectOrCreate?: Prisma.Escrito_porCreateOrConnectWithoutLivroInput | Prisma.Escrito_porCreateOrConnectWithoutLivroInput[]
  upsert?: Prisma.Escrito_porUpsertWithWhereUniqueWithoutLivroInput | Prisma.Escrito_porUpsertWithWhereUniqueWithoutLivroInput[]
  createMany?: Prisma.Escrito_porCreateManyLivroInputEnvelope
  set?: Prisma.Escrito_porWhereUniqueInput | Prisma.Escrito_porWhereUniqueInput[]
  disconnect?: Prisma.Escrito_porWhereUniqueInput | Prisma.Escrito_porWhereUniqueInput[]
  delete?: Prisma.Escrito_porWhereUniqueInput | Prisma.Escrito_porWhereUniqueInput[]
  connect?: Prisma.Escrito_porWhereUniqueInput | Prisma.Escrito_porWhereUniqueInput[]
  update?: Prisma.Escrito_porUpdateWithWhereUniqueWithoutLivroInput | Prisma.Escrito_porUpdateWithWhereUniqueWithoutLivroInput[]
  updateMany?: Prisma.Escrito_porUpdateManyWithWhereWithoutLivroInput | Prisma.Escrito_porUpdateManyWithWhereWithoutLivroInput[]
  deleteMany?: Prisma.Escrito_porScalarWhereInput | Prisma.Escrito_porScalarWhereInput[]
}

export type Escrito_porCreateNestedManyWithoutAutorInput = {
  create?: Prisma.XOR<Prisma.Escrito_porCreateWithoutAutorInput, Prisma.Escrito_porUncheckedCreateWithoutAutorInput> | Prisma.Escrito_porCreateWithoutAutorInput[] | Prisma.Escrito_porUncheckedCreateWithoutAutorInput[]
  connectOrCreate?: Prisma.Escrito_porCreateOrConnectWithoutAutorInput | Prisma.Escrito_porCreateOrConnectWithoutAutorInput[]
  createMany?: Prisma.Escrito_porCreateManyAutorInputEnvelope
  connect?: Prisma.Escrito_porWhereUniqueInput | Prisma.Escrito_porWhereUniqueInput[]
}

export type Escrito_porUncheckedCreateNestedManyWithoutAutorInput = {
  create?: Prisma.XOR<Prisma.Escrito_porCreateWithoutAutorInput, Prisma.Escrito_porUncheckedCreateWithoutAutorInput> | Prisma.Escrito_porCreateWithoutAutorInput[] | Prisma.Escrito_porUncheckedCreateWithoutAutorInput[]
  connectOrCreate?: Prisma.Escrito_porCreateOrConnectWithoutAutorInput | Prisma.Escrito_porCreateOrConnectWithoutAutorInput[]
  createMany?: Prisma.Escrito_porCreateManyAutorInputEnvelope
  connect?: Prisma.Escrito_porWhereUniqueInput | Prisma.Escrito_porWhereUniqueInput[]
}

export type Escrito_porUpdateManyWithoutAutorNestedInput = {
  create?: Prisma.XOR<Prisma.Escrito_porCreateWithoutAutorInput, Prisma.Escrito_porUncheckedCreateWithoutAutorInput> | Prisma.Escrito_porCreateWithoutAutorInput[] | Prisma.Escrito_porUncheckedCreateWithoutAutorInput[]
  connectOrCreate?: Prisma.Escrito_porCreateOrConnectWithoutAutorInput | Prisma.Escrito_porCreateOrConnectWithoutAutorInput[]
  upsert?: Prisma.Escrito_porUpsertWithWhereUniqueWithoutAutorInput | Prisma.Escrito_porUpsertWithWhereUniqueWithoutAutorInput[]
  createMany?: Prisma.Escrito_porCreateManyAutorInputEnvelope
  set?: Prisma.Escrito_porWhereUniqueInput | Prisma.Escrito_porWhereUniqueInput[]
  disconnect?: Prisma.Escrito_porWhereUniqueInput | Prisma.Escrito_porWhereUniqueInput[]
  delete?: Prisma.Escrito_porWhereUniqueInput | Prisma.Escrito_porWhereUniqueInput[]
  connect?: Prisma.Escrito_porWhereUniqueInput | Prisma.Escrito_porWhereUniqueInput[]
  update?: Prisma.Escrito_porUpdateWithWhereUniqueWithoutAutorInput | Prisma.Escrito_porUpdateWithWhereUniqueWithoutAutorInput[]
  updateMany?: Prisma.Escrito_porUpdateManyWithWhereWithoutAutorInput | Prisma.Escrito_porUpdateManyWithWhereWithoutAutorInput[]
  deleteMany?: Prisma.Escrito_porScalarWhereInput | Prisma.Escrito_porScalarWhereInput[]
}

export type Escrito_porUncheckedUpdateManyWithoutAutorNestedInput = {
  create?: Prisma.XOR<Prisma.Escrito_porCreateWithoutAutorInput, Prisma.Escrito_porUncheckedCreateWithoutAutorInput> | Prisma.Escrito_porCreateWithoutAutorInput[] | Prisma.Escrito_porUncheckedCreateWithoutAutorInput[]
  connectOrCreate?: Prisma.Escrito_porCreateOrConnectWithoutAutorInput | Prisma.Escrito_porCreateOrConnectWithoutAutorInput[]
  upsert?: Prisma.Escrito_porUpsertWithWhereUniqueWithoutAutorInput | Prisma.Escrito_porUpsertWithWhereUniqueWithoutAutorInput[]
  createMany?: Prisma.Escrito_porCreateManyAutorInputEnvelope
  set?: Prisma.Escrito_porWhereUniqueInput | Prisma.Escrito_porWhereUniqueInput[]
  disconnect?: Prisma.Escrito_porWhereUniqueInput | Prisma.Escrito_porWhereUniqueInput[]
  delete?: Prisma.Escrito_porWhereUniqueInput | Prisma.Escrito_porWhereUniqueInput[]
  connect?: Prisma.Escrito_porWhereUniqueInput | Prisma.Escrito_porWhereUniqueInput[]
  update?: Prisma.Escrito_porUpdateWithWhereUniqueWithoutAutorInput | Prisma.Escrito_porUpdateWithWhereUniqueWithoutAutorInput[]
  updateMany?: Prisma.Escrito_porUpdateManyWithWhereWithoutAutorInput | Prisma.Escrito_porUpdateManyWithWhereWithoutAutorInput[]
  deleteMany?: Prisma.Escrito_porScalarWhereInput | Prisma.Escrito_porScalarWhereInput[]
}

export type Escrito_porCreateWithoutLivroInput = {
  autor: Prisma.AutorCreateNestedOneWithoutLivrosInput
}

export type Escrito_porUncheckedCreateWithoutLivroInput = {
  autorId: number
}

export type Escrito_porCreateOrConnectWithoutLivroInput = {
  where: Prisma.Escrito_porWhereUniqueInput
  create: Prisma.XOR<Prisma.Escrito_porCreateWithoutLivroInput, Prisma.Escrito_porUncheckedCreateWithoutLivroInput>
}

export type Escrito_porCreateManyLivroInputEnvelope = {
  data: Prisma.Escrito_porCreateManyLivroInput | Prisma.Escrito_porCreateManyLivroInput[]
  skipDuplicates?: boolean
}

export type Escrito_porUpsertWithWhereUniqueWithoutLivroInput = {
  where: Prisma.Escrito_porWhereUniqueInput
  update: Prisma.XOR<Prisma.Escrito_porUpdateWithoutLivroInput, Prisma.Escrito_porUncheckedUpdateWithoutLivroInput>
  create: Prisma.XOR<Prisma.Escrito_porCreateWithoutLivroInput, Prisma.Escrito_porUncheckedCreateWithoutLivroInput>
}

export type Escrito_porUpdateWithWhereUniqueWithoutLivroInput = {
  where: Prisma.Escrito_porWhereUniqueInput
  data: Prisma.XOR<Prisma.Escrito_porUpdateWithoutLivroInput, Prisma.Escrito_porUncheckedUpdateWithoutLivroInput>
}

export type Escrito_porUpdateManyWithWhereWithoutLivroInput = {
  where: Prisma.Escrito_porScalarWhereInput
  data: Prisma.XOR<Prisma.Escrito_porUpdateManyMutationInput, Prisma.Escrito_porUncheckedUpdateManyWithoutLivroInput>
}

export type Escrito_porScalarWhereInput = {
  AND?: Prisma.Escrito_porScalarWhereInput | Prisma.Escrito_porScalarWhereInput[]
  OR?: Prisma.Escrito_porScalarWhereInput[]
  NOT?: Prisma.Escrito_porScalarWhereInput | Prisma.Escrito_porScalarWhereInput[]
  livroId?: Prisma.IntFilter<"Escrito_por"> | number
  autorId?: Prisma.IntFilter<"Escrito_por"> | number
}

export type Escrito_porCreateWithoutAutorInput = {
  livro: Prisma.LivroCreateNestedOneWithoutAutoresInput
}

export type Escrito_porUncheckedCreateWithoutAutorInput = {
  livroId: number
}

export type Escrito_porCreateOrConnectWithoutAutorInput = {
  where: Prisma.Escrito_porWhereUniqueInput
  create: Prisma.XOR<Prisma.Escrito_porCreateWithoutAutorInput, Prisma.Escrito_porUncheckedCreateWithoutAutorInput>
}

export type Escrito_porCreateManyAutorInputEnvelope = {
  data: Prisma.Escrito_porCreateManyAutorInput | Prisma.Escrito_porCreateManyAutorInput[]
  skipDuplicates?: boolean
}

export type Escrito_porUpsertWithWhereUniqueWithoutAutorInput = {
  where: Prisma.Escrito_porWhereUniqueInput
  update: Prisma.XOR<Prisma.Escrito_porUpdateWithoutAutorInput, Prisma.Escrito_porUncheckedUpdateWithoutAutorInput>
  create: Prisma.XOR<Prisma.Escrito_porCreateWithoutAutorInput, Prisma.Escrito_porUncheckedCreateWithoutAutorInput>
}

export type Escrito_porUpdateWithWhereUniqueWithoutAutorInput = {
  where: Prisma.Escrito_porWhereUniqueInput
  data: Prisma.XOR<Prisma.Escrito_porUpdateWithoutAutorInput, Prisma.Escrito_porUncheckedUpdateWithoutAutorInput>
}

export type Escrito_porUpdateManyWithWhereWithoutAutorInput = {
  where: Prisma.Escrito_porScalarWhereInput
  data: Prisma.XOR<Prisma.Escrito_porUpdateManyMutationInput, Prisma.Escrito_porUncheckedUpdateManyWithoutAutorInput>
}

export type Escrito_porCreateManyLivroInput = {
  autorId: number
}

export type Escrito_porUpdateWithoutLivroInput = {
  autor?: Prisma.AutorUpdateOneRequiredWithoutLivrosNestedInput
}

export type Escrito_porUncheckedUpdateWithoutLivroInput = {
  autorId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type Escrito_porUncheckedUpdateManyWithoutLivroInput = {
  autorId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type Escrito_porCreateManyAutorInput = {
  livroId: number
}

export type Escrito_porUpdateWithoutAutorInput = {
  livro?: Prisma.LivroUpdateOneRequiredWithoutAutoresNestedInput
}

export type Escrito_porUncheckedUpdateWithoutAutorInput = {
  livroId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type Escrito_porUncheckedUpdateManyWithoutAutorInput = {
  livroId?: Prisma.IntFieldUpdateOperationsInput | number
}



export type Escrito_porSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  livroId?: boolean
  autorId?: boolean
  autor?: boolean | Prisma.AutorDefaultArgs<ExtArgs>
  livro?: boolean | Prisma.LivroDefaultArgs<ExtArgs>
}, ExtArgs["result"]["escrito_por"]>

export type Escrito_porSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  livroId?: boolean
  autorId?: boolean
  autor?: boolean | Prisma.AutorDefaultArgs<ExtArgs>
  livro?: boolean | Prisma.LivroDefaultArgs<ExtArgs>
}, ExtArgs["result"]["escrito_por"]>

export type Escrito_porSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  livroId?: boolean
  autorId?: boolean
  autor?: boolean | Prisma.AutorDefaultArgs<ExtArgs>
  livro?: boolean | Prisma.LivroDefaultArgs<ExtArgs>
}, ExtArgs["result"]["escrito_por"]>

export type Escrito_porSelectScalar = {
  livroId?: boolean
  autorId?: boolean
}

export type Escrito_porOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"livroId" | "autorId", ExtArgs["result"]["escrito_por"]>
export type Escrito_porInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  autor?: boolean | Prisma.AutorDefaultArgs<ExtArgs>
  livro?: boolean | Prisma.LivroDefaultArgs<ExtArgs>
}
export type Escrito_porIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  autor?: boolean | Prisma.AutorDefaultArgs<ExtArgs>
  livro?: boolean | Prisma.LivroDefaultArgs<ExtArgs>
}
export type Escrito_porIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  autor?: boolean | Prisma.AutorDefaultArgs<ExtArgs>
  livro?: boolean | Prisma.LivroDefaultArgs<ExtArgs>
}

export type $Escrito_porPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Escrito_por"
  objects: {
    autor: Prisma.$AutorPayload<ExtArgs>
    livro: Prisma.$LivroPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    livroId: number
    autorId: number
  }, ExtArgs["result"]["escrito_por"]>
  composites: {}
}

export type Escrito_porGetPayload<S extends boolean | null | undefined | Escrito_porDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$Escrito_porPayload, S>

export type Escrito_porCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<Escrito_porFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Escrito_porCountAggregateInputType | true
  }

export interface Escrito_porDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Escrito_por'], meta: { name: 'Escrito_por' } }
  /**
   * Find zero or one Escrito_por that matches the filter.
   * @param {Escrito_porFindUniqueArgs} args - Arguments to find a Escrito_por
   * @example
   * // Get one Escrito_por
   * const escrito_por = await prisma.escrito_por.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends Escrito_porFindUniqueArgs>(args: Prisma.SelectSubset<T, Escrito_porFindUniqueArgs<ExtArgs>>): Prisma.Prisma__Escrito_porClient<runtime.Types.Result.GetResult<Prisma.$Escrito_porPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Escrito_por that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {Escrito_porFindUniqueOrThrowArgs} args - Arguments to find a Escrito_por
   * @example
   * // Get one Escrito_por
   * const escrito_por = await prisma.escrito_por.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends Escrito_porFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, Escrito_porFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__Escrito_porClient<runtime.Types.Result.GetResult<Prisma.$Escrito_porPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Escrito_por that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Escrito_porFindFirstArgs} args - Arguments to find a Escrito_por
   * @example
   * // Get one Escrito_por
   * const escrito_por = await prisma.escrito_por.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends Escrito_porFindFirstArgs>(args?: Prisma.SelectSubset<T, Escrito_porFindFirstArgs<ExtArgs>>): Prisma.Prisma__Escrito_porClient<runtime.Types.Result.GetResult<Prisma.$Escrito_porPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Escrito_por that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Escrito_porFindFirstOrThrowArgs} args - Arguments to find a Escrito_por
   * @example
   * // Get one Escrito_por
   * const escrito_por = await prisma.escrito_por.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends Escrito_porFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, Escrito_porFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__Escrito_porClient<runtime.Types.Result.GetResult<Prisma.$Escrito_porPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Escrito_pors that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Escrito_porFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Escrito_pors
   * const escrito_pors = await prisma.escrito_por.findMany()
   * 
   * // Get first 10 Escrito_pors
   * const escrito_pors = await prisma.escrito_por.findMany({ take: 10 })
   * 
   * // Only select the `livroId`
   * const escrito_porWithLivroIdOnly = await prisma.escrito_por.findMany({ select: { livroId: true } })
   * 
   */
  findMany<T extends Escrito_porFindManyArgs>(args?: Prisma.SelectSubset<T, Escrito_porFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Escrito_porPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Escrito_por.
   * @param {Escrito_porCreateArgs} args - Arguments to create a Escrito_por.
   * @example
   * // Create one Escrito_por
   * const Escrito_por = await prisma.escrito_por.create({
   *   data: {
   *     // ... data to create a Escrito_por
   *   }
   * })
   * 
   */
  create<T extends Escrito_porCreateArgs>(args: Prisma.SelectSubset<T, Escrito_porCreateArgs<ExtArgs>>): Prisma.Prisma__Escrito_porClient<runtime.Types.Result.GetResult<Prisma.$Escrito_porPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Escrito_pors.
   * @param {Escrito_porCreateManyArgs} args - Arguments to create many Escrito_pors.
   * @example
   * // Create many Escrito_pors
   * const escrito_por = await prisma.escrito_por.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends Escrito_porCreateManyArgs>(args?: Prisma.SelectSubset<T, Escrito_porCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Escrito_pors and returns the data saved in the database.
   * @param {Escrito_porCreateManyAndReturnArgs} args - Arguments to create many Escrito_pors.
   * @example
   * // Create many Escrito_pors
   * const escrito_por = await prisma.escrito_por.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Escrito_pors and only return the `livroId`
   * const escrito_porWithLivroIdOnly = await prisma.escrito_por.createManyAndReturn({
   *   select: { livroId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends Escrito_porCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, Escrito_porCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Escrito_porPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Escrito_por.
   * @param {Escrito_porDeleteArgs} args - Arguments to delete one Escrito_por.
   * @example
   * // Delete one Escrito_por
   * const Escrito_por = await prisma.escrito_por.delete({
   *   where: {
   *     // ... filter to delete one Escrito_por
   *   }
   * })
   * 
   */
  delete<T extends Escrito_porDeleteArgs>(args: Prisma.SelectSubset<T, Escrito_porDeleteArgs<ExtArgs>>): Prisma.Prisma__Escrito_porClient<runtime.Types.Result.GetResult<Prisma.$Escrito_porPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Escrito_por.
   * @param {Escrito_porUpdateArgs} args - Arguments to update one Escrito_por.
   * @example
   * // Update one Escrito_por
   * const escrito_por = await prisma.escrito_por.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends Escrito_porUpdateArgs>(args: Prisma.SelectSubset<T, Escrito_porUpdateArgs<ExtArgs>>): Prisma.Prisma__Escrito_porClient<runtime.Types.Result.GetResult<Prisma.$Escrito_porPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Escrito_pors.
   * @param {Escrito_porDeleteManyArgs} args - Arguments to filter Escrito_pors to delete.
   * @example
   * // Delete a few Escrito_pors
   * const { count } = await prisma.escrito_por.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends Escrito_porDeleteManyArgs>(args?: Prisma.SelectSubset<T, Escrito_porDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Escrito_pors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Escrito_porUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Escrito_pors
   * const escrito_por = await prisma.escrito_por.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends Escrito_porUpdateManyArgs>(args: Prisma.SelectSubset<T, Escrito_porUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Escrito_pors and returns the data updated in the database.
   * @param {Escrito_porUpdateManyAndReturnArgs} args - Arguments to update many Escrito_pors.
   * @example
   * // Update many Escrito_pors
   * const escrito_por = await prisma.escrito_por.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Escrito_pors and only return the `livroId`
   * const escrito_porWithLivroIdOnly = await prisma.escrito_por.updateManyAndReturn({
   *   select: { livroId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends Escrito_porUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, Escrito_porUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Escrito_porPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Escrito_por.
   * @param {Escrito_porUpsertArgs} args - Arguments to update or create a Escrito_por.
   * @example
   * // Update or create a Escrito_por
   * const escrito_por = await prisma.escrito_por.upsert({
   *   create: {
   *     // ... data to create a Escrito_por
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Escrito_por we want to update
   *   }
   * })
   */
  upsert<T extends Escrito_porUpsertArgs>(args: Prisma.SelectSubset<T, Escrito_porUpsertArgs<ExtArgs>>): Prisma.Prisma__Escrito_porClient<runtime.Types.Result.GetResult<Prisma.$Escrito_porPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Escrito_pors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Escrito_porCountArgs} args - Arguments to filter Escrito_pors to count.
   * @example
   * // Count the number of Escrito_pors
   * const count = await prisma.escrito_por.count({
   *   where: {
   *     // ... the filter for the Escrito_pors we want to count
   *   }
   * })
  **/
  count<T extends Escrito_porCountArgs>(
    args?: Prisma.Subset<T, Escrito_porCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Escrito_porCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Escrito_por.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Escrito_porAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Escrito_porAggregateArgs>(args: Prisma.Subset<T, Escrito_porAggregateArgs>): Prisma.PrismaPromise<GetEscrito_porAggregateType<T>>

  /**
   * Group by Escrito_por.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Escrito_porGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends Escrito_porGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: Escrito_porGroupByArgs['orderBy'] }
      : { orderBy?: Escrito_porGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, Escrito_porGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEscrito_porGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Escrito_por model
 */
readonly fields: Escrito_porFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Escrito_por.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__Escrito_porClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  autor<T extends Prisma.AutorDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AutorDefaultArgs<ExtArgs>>): Prisma.Prisma__AutorClient<runtime.Types.Result.GetResult<Prisma.$AutorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  livro<T extends Prisma.LivroDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LivroDefaultArgs<ExtArgs>>): Prisma.Prisma__LivroClient<runtime.Types.Result.GetResult<Prisma.$LivroPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Escrito_por model
 */
export interface Escrito_porFieldRefs {
  readonly livroId: Prisma.FieldRef<"Escrito_por", 'Int'>
  readonly autorId: Prisma.FieldRef<"Escrito_por", 'Int'>
}
    

// Custom InputTypes
/**
 * Escrito_por findUnique
 */
export type Escrito_porFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Escrito_por
   */
  select?: Prisma.Escrito_porSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Escrito_por
   */
  omit?: Prisma.Escrito_porOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Escrito_porInclude<ExtArgs> | null
  /**
   * Filter, which Escrito_por to fetch.
   */
  where: Prisma.Escrito_porWhereUniqueInput
}

/**
 * Escrito_por findUniqueOrThrow
 */
export type Escrito_porFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Escrito_por
   */
  select?: Prisma.Escrito_porSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Escrito_por
   */
  omit?: Prisma.Escrito_porOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Escrito_porInclude<ExtArgs> | null
  /**
   * Filter, which Escrito_por to fetch.
   */
  where: Prisma.Escrito_porWhereUniqueInput
}

/**
 * Escrito_por findFirst
 */
export type Escrito_porFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Escrito_por
   */
  select?: Prisma.Escrito_porSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Escrito_por
   */
  omit?: Prisma.Escrito_porOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Escrito_porInclude<ExtArgs> | null
  /**
   * Filter, which Escrito_por to fetch.
   */
  where?: Prisma.Escrito_porWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Escrito_pors to fetch.
   */
  orderBy?: Prisma.Escrito_porOrderByWithRelationInput | Prisma.Escrito_porOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Escrito_pors.
   */
  cursor?: Prisma.Escrito_porWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Escrito_pors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Escrito_pors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Escrito_pors.
   */
  distinct?: Prisma.Escrito_porScalarFieldEnum | Prisma.Escrito_porScalarFieldEnum[]
}

/**
 * Escrito_por findFirstOrThrow
 */
export type Escrito_porFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Escrito_por
   */
  select?: Prisma.Escrito_porSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Escrito_por
   */
  omit?: Prisma.Escrito_porOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Escrito_porInclude<ExtArgs> | null
  /**
   * Filter, which Escrito_por to fetch.
   */
  where?: Prisma.Escrito_porWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Escrito_pors to fetch.
   */
  orderBy?: Prisma.Escrito_porOrderByWithRelationInput | Prisma.Escrito_porOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Escrito_pors.
   */
  cursor?: Prisma.Escrito_porWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Escrito_pors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Escrito_pors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Escrito_pors.
   */
  distinct?: Prisma.Escrito_porScalarFieldEnum | Prisma.Escrito_porScalarFieldEnum[]
}

/**
 * Escrito_por findMany
 */
export type Escrito_porFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Escrito_por
   */
  select?: Prisma.Escrito_porSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Escrito_por
   */
  omit?: Prisma.Escrito_porOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Escrito_porInclude<ExtArgs> | null
  /**
   * Filter, which Escrito_pors to fetch.
   */
  where?: Prisma.Escrito_porWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Escrito_pors to fetch.
   */
  orderBy?: Prisma.Escrito_porOrderByWithRelationInput | Prisma.Escrito_porOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Escrito_pors.
   */
  cursor?: Prisma.Escrito_porWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Escrito_pors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Escrito_pors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Escrito_pors.
   */
  distinct?: Prisma.Escrito_porScalarFieldEnum | Prisma.Escrito_porScalarFieldEnum[]
}

/**
 * Escrito_por create
 */
export type Escrito_porCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Escrito_por
   */
  select?: Prisma.Escrito_porSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Escrito_por
   */
  omit?: Prisma.Escrito_porOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Escrito_porInclude<ExtArgs> | null
  /**
   * The data needed to create a Escrito_por.
   */
  data: Prisma.XOR<Prisma.Escrito_porCreateInput, Prisma.Escrito_porUncheckedCreateInput>
}

/**
 * Escrito_por createMany
 */
export type Escrito_porCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Escrito_pors.
   */
  data: Prisma.Escrito_porCreateManyInput | Prisma.Escrito_porCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Escrito_por createManyAndReturn
 */
export type Escrito_porCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Escrito_por
   */
  select?: Prisma.Escrito_porSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Escrito_por
   */
  omit?: Prisma.Escrito_porOmit<ExtArgs> | null
  /**
   * The data used to create many Escrito_pors.
   */
  data: Prisma.Escrito_porCreateManyInput | Prisma.Escrito_porCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Escrito_porIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Escrito_por update
 */
export type Escrito_porUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Escrito_por
   */
  select?: Prisma.Escrito_porSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Escrito_por
   */
  omit?: Prisma.Escrito_porOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Escrito_porInclude<ExtArgs> | null
  /**
   * The data needed to update a Escrito_por.
   */
  data: Prisma.XOR<Prisma.Escrito_porUpdateInput, Prisma.Escrito_porUncheckedUpdateInput>
  /**
   * Choose, which Escrito_por to update.
   */
  where: Prisma.Escrito_porWhereUniqueInput
}

/**
 * Escrito_por updateMany
 */
export type Escrito_porUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Escrito_pors.
   */
  data: Prisma.XOR<Prisma.Escrito_porUpdateManyMutationInput, Prisma.Escrito_porUncheckedUpdateManyInput>
  /**
   * Filter which Escrito_pors to update
   */
  where?: Prisma.Escrito_porWhereInput
  /**
   * Limit how many Escrito_pors to update.
   */
  limit?: number
}

/**
 * Escrito_por updateManyAndReturn
 */
export type Escrito_porUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Escrito_por
   */
  select?: Prisma.Escrito_porSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Escrito_por
   */
  omit?: Prisma.Escrito_porOmit<ExtArgs> | null
  /**
   * The data used to update Escrito_pors.
   */
  data: Prisma.XOR<Prisma.Escrito_porUpdateManyMutationInput, Prisma.Escrito_porUncheckedUpdateManyInput>
  /**
   * Filter which Escrito_pors to update
   */
  where?: Prisma.Escrito_porWhereInput
  /**
   * Limit how many Escrito_pors to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Escrito_porIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Escrito_por upsert
 */
export type Escrito_porUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Escrito_por
   */
  select?: Prisma.Escrito_porSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Escrito_por
   */
  omit?: Prisma.Escrito_porOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Escrito_porInclude<ExtArgs> | null
  /**
   * The filter to search for the Escrito_por to update in case it exists.
   */
  where: Prisma.Escrito_porWhereUniqueInput
  /**
   * In case the Escrito_por found by the `where` argument doesn't exist, create a new Escrito_por with this data.
   */
  create: Prisma.XOR<Prisma.Escrito_porCreateInput, Prisma.Escrito_porUncheckedCreateInput>
  /**
   * In case the Escrito_por was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.Escrito_porUpdateInput, Prisma.Escrito_porUncheckedUpdateInput>
}

/**
 * Escrito_por delete
 */
export type Escrito_porDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Escrito_por
   */
  select?: Prisma.Escrito_porSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Escrito_por
   */
  omit?: Prisma.Escrito_porOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Escrito_porInclude<ExtArgs> | null
  /**
   * Filter which Escrito_por to delete.
   */
  where: Prisma.Escrito_porWhereUniqueInput
}

/**
 * Escrito_por deleteMany
 */
export type Escrito_porDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Escrito_pors to delete
   */
  where?: Prisma.Escrito_porWhereInput
  /**
   * Limit how many Escrito_pors to delete.
   */
  limit?: number
}

/**
 * Escrito_por without action
 */
export type Escrito_porDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Escrito_por
   */
  select?: Prisma.Escrito_porSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Escrito_por
   */
  omit?: Prisma.Escrito_porOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Escrito_porInclude<ExtArgs> | null
}
