
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model Account
 * 
 */
export type Account = Prisma.AccountModel
/**
 * Model Session
 * 
 */
export type Session = Prisma.SessionModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model VerificationToken
 * 
 */
export type VerificationToken = Prisma.VerificationTokenModel
/**
 * Model Livro
 * 
 */
export type Livro = Prisma.LivroModel
/**
 * Model Colecao
 * 
 */
export type Colecao = Prisma.ColecaoModel
/**
 * Model Autor
 * 
 */
export type Autor = Prisma.AutorModel
/**
 * Model Escrito_por
 * 
 */
export type Escrito_por = Prisma.Escrito_porModel
/**
 * Model Postagem
 * 
 */
export type Postagem = Prisma.PostagemModel
/**
 * Model Comentario
 * 
 */
export type Comentario = Prisma.ComentarioModel
/**
 * Model Biblioteca
 * 
 */
export type Biblioteca = Prisma.BibliotecaModel
/**
 * Model Curtida
 * 
 */
export type Curtida = Prisma.CurtidaModel
/**
 * Model Amigos
 * 
 */
export type Amigos = Prisma.AmigosModel
